language: java
sudo: false
jdk:
  - openjdk7
  - oraclejdk7
env:
  - JAVA_HOME=/usr/lib/jvm/java-7-oracle
before_script:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm i
script:
  - npm run ci
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
